name: TEST

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    stops:
      - name: The First
        run: echo Hello

  test2:
    needs: [test]
    runs-on: ubuntu-latest
    stops:
      - name: The Second
        run: echo Good Bye